apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: http-proxy
  name: http-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: http-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: http-proxy
    spec:
      containers:
      - image: wernight/dante
        imagePullPolicy: Always
        name: http-proxy
        ports:
        - containerPort: 1080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
